#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m rule --add app="^Installer$" manage=off
yabai -m rule --add app="^Disk Utility$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Keychain Access$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Font Book$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Telegram$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Spark$" manage=off
yabai -m rule --add app="^Mail$" manage=off
yabai -m rule --add app="^Harvest$" manage=off

# bsp or float (default: float)
yabai -m config layout bsp

# Set all padding and gaps to 20pt (default: 0)
yabai -m config top_padding    10
yabai -m config bottom_padding 10
yabai -m config left_padding   10
yabai -m config right_padding  10
yabai -m config window_gap     10

# # set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
# yabai -m config focus_follows_mouse autofocus

# modify window shadows (default: on, options: on, off, float)
# example: show shadows only for floating windows
yabai -m config window_shadow float

# add 20 padding to the top and 0 padding to the bottom of every space located on the main display
# yabai -m config external_bar main:30:0

# Border settings
yabai -m config window_border on
yabai -m config window_border_blur off
yabai -m config window_border_width 1
yabai -m config active_window_border_color 0xFFd3c6aa
yabai -m config normal_window_border_color 0xcc333333
