"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false

format = """
$directory\
$git_branch\
$git_status\
$php\
$nodejs\
$jobs\
$line_break\
$character
"""

[character]
success_symbol = "[󰅂](yellow)"
error_symbol = "[󰅂](red)"

[directory]
truncation_length = 3
truncate_to_repo = false
style = "yellow"

[git_branch]
format = "[$symbol($branch)](green) "
symbol = "󰘬 "

[git_status]
format = "([$ahead_behind$all_status](style) )"
stashed = "[󰬀${count}](white)"
ahead = "↑${count}"
behind = "↓${count}"
staged = "[󰬀${count}](green)"
untracked = "[󰬂${count}](blue)"
modified = "[󰫺${count}](yellow)"
deleted = "[󰫱${count}](red)"

[nodejs]
format = "[$symbol$version](green) "
version_format = "${major}.${minor}"

[php]
symbol = " "
format = "[$symbol$version](blue) "
version_format = "${major}.${minor}"

