[colors]
ansi = [
    '#2d353b',
    '#e67e80',
    '#a7c080',
    '#dbbc7f',
    '#7fbbb3',
    '#d699b6',
    '#83c092',
    '#7a8478',
]
background = '#2d353b'
brights = [
    '#d3c6aa',
    '#e67e80',
    '#a7c080',
    '#dbbc7f',
    '#7fbbb3',
    '#d699b6',
    '#83c092',
    '#7a8478',
]
cursor_bg = '#d3c6aa'
cursor_border = '#d3c6aa'
cursor_fg = '#333c43'
foreground = '#d3c6aa'
selection_bg = '#5c3f4f'
selection_fg = '#d3c6aa'
[colors.indexed]

[metadata]
author = "Frank Friberg"
name = "Neverforest"
